import django
from django.db import transaction
from .models import MeasurementER, MeasurementTB, TestER, TestTB

django.setup()

#----------------------------------------------- método con hilos ----------------------------------------------
#@transaction.atomic
def create_objects(data):
    obj = data[0]
    if isinstance(obj, MeasurementER):
        MeasurementER.objects.bulk_create(data)
    if isinstance(obj, MeasurementTB):
        MeasurementTB.objects.bulk_create(data)

def read_excel_chunk(file, chunk_size, test):
    worksheet = file.active
    rows = worksheet.iter_rows(min_row=2, values_only=True)
    chunk = []
    if isinstance(test, TestER):
        for row in rows:
            chunk.append(MeasurementER(test_electrical_result_fk=test,
                                        #item=row[0],
                                        time=row[1],
                                        mag_v1=row[2],
                                        mag_v2=row[3],
                                        mag_v3=row[4],
                                        ang_v1=row[5],
                                        ang_v2=row[6],
                                        ang_v3=row[7],
                                        mag_i1=row[8],
                                        mag_i2=row[9],
                                        mag_i3=row[10],
                                        ang_i1=row[11],
                                        ang_i2=row[12],
                                        ang_i3=row[13],
                                        v1_freq=row[14],
                                        v2_freq=row[15],
                                        v3_freq=row[16],
                                        pf1_1=row[17],
                                        pf2_2=row[18],
                                        pf3_3=row[19],
                                        kw_1=row[20],
                                        kw_2=row[21],
                                        kw_3=row[22],
                                        kvar_1=row[23],
                                        kvar_2=row[24],
                                        kvar_3=row[25],
                                        ks_1=row[26],
                                        ks_2=row[27],
                                        ks_3=row[28],
                                        ckwh_1=row[29],
                                        ckwh_2=row[30],
                                        ckwh_3=row[31],
                                        lsskw_1=row[32],
                                        lsskw_2=row[33],
                                        lsskw_3=row[34],
                                        dv_u2=row[35],
                                        dv_u0=row[36],
                                        dvf_u2=row[37],
                                        dvf_u0=row[38],
                                        di_u2=row[39],
                                        di_u0=row[40],
                                        dif_u2=row[41],
                                        dif_u0=row[42],
                                        u0_mag=row[43],
                                        u1_mag=row[44],
                                        u2_mag=row[45],
                                        u0_ang =row[46],
                                        u1_ang =row[47],
                                        u2_ang =row[48],
                                        i0_mag =row[49],
                                        i1_mag =row[50],
                                        i2_mag =row[51],
                                        i0_ang =row[52],
                                        i1_ang =row[53],
                                        i2_ang =row[54],
                                        eff1 =row[55],
                                        eff2 =row[56],
                                        eff3 =row[57],
                                        torque1 =row[58],
                                        torque2 =row[59],
                                        torque3 =row[60],
                                        load1_percen =row[61],
                                        load2_percen =row[62],
                                        load3_percen =row[63],
                                        load1_hp =row[64],
                                        load2_hp =row[65],
                                        load3_hp =row[66],
                                        rpm =row[67],
                                        db1 =row[68],
                                        db2 =row[69],
                                        db3 =row[70],
                                        thd_v1 =row[71],
                                        thd_v2 =row[72],
                                        thd_v3 =row[73],
                                        thdg_v1 =row[74],
                                        thdg_v2 =row[75],
                                        thdg_v3 =row[76],
                                        thd_i1 =row[77],
                                        thd_i2 =row[78],
                                        thd_i3 =row[79],
                                        thds_v1 =row[80],
                                        thds_v2 =row[81],
                                        thds_v3 =row[82],
                                        vh1_v1 =row[83],
                                        vh1_v2 =row[84],
                                        vh1_v3 =row[85],
                                        vh1_v4 =row[86],
                                        vh1_v5 =row[87],
                                        vh1_v6 =row[88],
                                        vh1_v7 =row[89],
                                        vh1_v8 =row[90],
                                        vh1_v9 =row[91],
                                        vh1_v10 =row[92],
                                        vh1_v11 =row[93],
                                        vh1_v12 =row[94],
                                        vh1_v13 =row[95],
                                        vh1_v14 =row[96],
                                        vh1_v15 =row[97],
                                        vh1_v16 =row[98],
                                        vh1_v17 =row[99],
                                        vh1_v18 =row[100],
                                        vh1_v19 =row[101],
                                        vh1_v20 =row[102],
                                        vh1_v21 =row[103],
                                        vh1_v22 =row[104],
                                        vh1_v23 =row[105],
                                        vh1_v24 =row[106],
                                        vh1_v25 =row[107],
                                        vh2_v1 =row[108],
                                        vh2_v2 =row[109],
                                        vh2_v3 =row[110],
                                        vh2_v4 =row[111],
                                        vh2_v5 =row[112],
                                        vh2_v6 =row[113],
                                        vh2_v7 =row[114],
                                        vh2_v8 =row[115],
                                        vh2_v9 =row[116],
                                        vh2_v10 =row[117],
                                        vh2_v11 =row[118],
                                        vh2_v12 =row[119],
                                        vh2_v13 =row[120],
                                        vh2_v14 =row[121],
                                        vh2_v15 =row[122],
                                        vh2_v16 =row[123],
                                        vh2_v17 =row[124],
                                        vh2_v18 =row[125],
                                        vh2_v19 =row[126],
                                        vh2_v20 =row[127],
                                        vh2_v21 =row[128],
                                        vh2_v22 =row[129],
                                        vh2_v23 =row[130],
                                        vh2_v24 =row[131],
                                        vh2_v25 =row[132],
                                        vh3_v1 =row[133],
                                        vh3_v2 =row[134],
                                        vh3_v3 =row[135],
                                        vh3_v4 =row[136],
                                        vh3_v5 =row[137],
                                        vh3_v6 =row[138],
                                        vh3_v7 =row[139],
                                        vh3_v8 =row[140],
                                        vh3_v9 =row[141],
                                        vh3_v10 =row[142],
                                        vh3_v11 =row[143],
                                        vh3_v12 =row[144],
                                        vh3_v13 =row[145],
                                        vh3_v14 =row[146],
                                        vh3_v15 =row[147],
                                        vh3_v16 =row[148],
                                        vh3_v17 =row[149],
                                        vh3_v18 =row[150],
                                        vh3_v19 =row[151],
                                        vh3_v20 =row[152],
                                        vh3_v21 =row[153],
                                        vh3_v22 =row[154],
                                        vh3_v23 =row[155],
                                        vh3_v24 =row[156],
                                        vh3_v25 =row[157],
                                        ih1_v1 =row[158],
                                        ih1_v2 =row[159],
                                        ih1_v3 =row[160],
                                        ih1_v4 =row[161],
                                        ih1_v5 =row[162],
                                        ih1_v6 =row[163],
                                        ih1_v7 =row[164],
                                        ih1_v8 =row[165],
                                        ih1_v9 =row[166],
                                        ih1_v10 =row[167],
                                        ih1_v11 =row[168],
                                        ih1_v12 =row[169],
                                        ih1_v13 =row[170],
                                        ih1_v14 =row[171],
                                        ih1_v15 =row[172],
                                        ih1_v16 =row[173],
                                        ih1_v17 =row[174],
                                        ih1_v18 =row[175],
                                        ih1_v19 =row[176],
                                        ih1_v20 =row[177],
                                        ih1_v21 =row[178],
                                        ih1_v22 =row[179],
                                        ih1_v23 =row[180],
                                        ih1_v24 =row[181],
                                        ih1_v25 =row[182],
                                        ih2_v1 =row[183],
                                        ih2_v2 =row[184],
                                        ih2_v3 =row[185],
                                        ih2_v4 =row[186],
                                        ih2_v5 =row[187],
                                        ih2_v6 =row[188],
                                        ih2_v7 =row[189],
                                        ih2_v8 =row[190],
                                        ih2_v9 =row[191],
                                        ih2_v10 =row[192],
                                        ih2_v11 =row[193],
                                        ih2_v12 =row[194],
                                        ih2_v13 =row[195],
                                        ih2_v14 =row[196],
                                        ih2_v15 =row[197],
                                        ih2_v16 =row[198],
                                        ih2_v17 =row[199],
                                        ih2_v18 =row[200],
                                        ih2_v19 =row[201],
                                        ih2_v20 =row[202],
                                        ih2_v21 =row[203],
                                        ih2_v22 =row[204],
                                        ih2_v23 =row[205],
                                        ih2_v24 =row[206],
                                        ih2_v25 =row[207],
                                        ih3_v1 =row[208],
                                        ih3_v2 =row[209],
                                        ih3_v3 =row[210],
                                        ih3_v4 =row[211],
                                        ih3_v5 =row[212],
                                        ih3_v6 =row[213],
                                        ih3_v7 =row[214],
                                        ih3_v8 =row[215],
                                        ih3_v9 =row[216],
                                        ih3_v10 =row[217],
                                        ih3_v11 =row[218],
                                        ih3_v12 =row[219],
                                        ih3_v13 =row[220],
                                        ih3_v14 =row[221],
                                        ih3_v15 =row[222],
                                        ih3_v16 =row[223],
                                        ih3_v17 =row[224],
                                        ih3_v18 =row[225],
                                        ih3_v19 =row[226],
                                        ih3_v20 =row[227],
                                        ih3_v21 =row[228],
                                        ih3_v22 =row[229],
                                        ih3_v23 =row[230],
                                        ih3_v24 =row[231],
                                        ih3_v25 =row[232]))
            if len(chunk) == chunk_size:
                yield chunk
                chunk = []
    if isinstance(test, TestTB):
        for row in rows:
            chunk.append(MeasurementTB(test_transient_boot_fk=test,
                                        #item=row[0],
                                        time=row[0],
                                        ia=row[1],
                                        ib=row[2],
                                        ic=row[3],
                                        va=row[4],
                                        vb=row[5],
                                        vc=row[6],
                                       ))
            if len(chunk) == chunk_size:
                yield chunk
                chunk = []
    if chunk:
        yield chunk

